"""fis

Revision ID: 7c174c705a5a
Revises: 
Create Date: 2022-04-22 01:35:43.352568

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7c174c705a5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flex_status', 'enterTime',
                    existing_type=sa.DATETIME(),
                    nullable=True)
    op.alter_column('flex_status', 'exitTime',
                    existing_type=sa.DATETIME(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flex_status', 'exitTime',
                    existing_type=sa.DATETIME(),
                    nullable=False)
    op.alter_column('flex_status', 'enterTime',
                    existing_type=sa.DATETIME(),
                    nullable=False)
    # ### end Alembic commands ###
