"""adding columnqs

Revision ID: c7d9cb770a1c
Revises: 
Create Date: 2022-04-29 02:06:47.069409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d9cb770a1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('assigned_id')

    with op.batch_alter_table('flex_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue', sa.String(length=100), nullable=True))
        batch_op.alter_column('enterTime',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('exitTime',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flex_status', schema=None) as batch_op:
        batch_op.alter_column('exitTime',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('enterTime',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('issue')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_id', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
