"""ch2 columnqs

Revision ID: eb08adf3ab5e
Revises: c7d9cb770a1c
Create Date: 2022-04-29 02:41:09.298218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb08adf3ab5e'
down_revision = 'c7d9cb770a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flex_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flex_status', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
